---
version: '3.7'

services:
  postgres:
    image: library/postgres:10.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/pgdata
      - POSTGRES_DB=airflow
    restart: unless-stopped
  redis:
    image: library/redis:4.0.11
    ports:
      - 6379:6379
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}

  webserver:
    image: puckel/docker-airflow:1.9.0-4
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=${FERNET_KEY}
      - EXECUTOR=Celery
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=airflow
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./airflow_dags:/usr/local/airflow/dags
      - ./airflow_plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: puckel/docker-airflow:1.9.0-4
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    image: puckel/docker-airflow:1.9.0-4
    restart: unless-stopped
    depends_on:
      - webserver
    volumes:
      - ./airflow_dags:/usr/local/airflow/dags
      - ./airflow_plugins:/usr/local/airflow/plugins
    environment:
      - LOAD_EX=n
      - FERNET_KEY=${FERNET_KEY}
      - EXECUTOR=Celery
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=airflow
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: scheduler

  worker:
    image: puckel/docker-airflow:1.9.0-4
    restart: unless-stopped
    depends_on:
      - scheduler
    volumes:
      - ./airflow_dags:/usr/local/airflow/dags
      - ./airflow_plugins:/usr/local/airflow/plugins
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - EXECUTOR=Celery
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=airflow
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: worker

# vim:ft=yaml st=2 sts=2 sw=2:
